---
title: "Lab2_Script"
author: "Marcela Morassi"
date: "9/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


StartUp
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)
library(dplyr)
library(ggplot2)
library(ggforce)
library(vegan)
theme_set(theme_classic()) # Set the theme


setwd("C:/Users/Marcela Morassi/Documents/Github/HeterogeneityLab")

data <- read.csv("full_data_F21.csv")
old_data <- read.csv("F20_heterogeneity_data.csv")

```

Calibrating Canopy Estimates
```{r}
regression = lm(Percent_Cnpy_Open ~ Canopy, data = data)
regression
summary(regression)
# Note that you should go with the "Multiple R-squared," not "Adjusted R-squared"

ggplot(data = data, aes(x=Canopy, y=Percent_Cnpy_Open)) + geom_point() + 
  geom_smooth(method = "lm", se = FALSE, color = "grey") +
  geom_jitter(height = 0, width = .15) +
  theme_classic() + xlab("Subjective Canopy Cover") + ylab("Percent Openness")

ggsave("Calibrating Canopy Estimates.png")

```

Relationship between canopy and ground cover pt. 1
```{r}
#canopy 0
zero_canopy <- data %>% 
  filter(Canopy == 0)

table_zero <- xtabs(~Ground + Shrub, data= zero_canopy)
 
chisq.test(table_zero)
table0_freq <- as.data.frame( table_zero/sum(table_zero) ) %>% 
  mutate(cover = 0)

table0_freq %>% 
  ggplot(aes(x = Ground, y = Shrub)) +
  geom_tile(aes(fill = Freq)) +
  scale_fill_viridis_c() +
  coord_fixed() +
  geom_label(aes(label = round(Freq, 3)),
            label.size = 0, # Keep this as is
            color = "white", # Text color
            fill = "#00000010", # Slight background around text to make it more legible
            size = 5) # text size
ggsave("Canopy Cover 0.png")  

#canopy 1
one_canopy <- data %>% 
  filter(Canopy == 1)

table_one <- xtabs(~Ground + Shrub, data= one_canopy)
 
chisq.test(table_one)
table1_freq <- as.data.frame( table_one/sum(table_one) )%>% 
  mutate(cover = 1)

table1_freq %>% 
  ggplot(aes(x = Ground, y = Shrub)) +
  geom_tile(aes(fill = Freq)) +
  scale_fill_viridis_c() +
  coord_fixed() +
  geom_label(aes(label = round(Freq, 3)),
            label.size = 0, # Keep this as is
            color = "white", # Text color
            fill = "#00000010", # Slight background around text to make it more legible
            size = 5) # text size
ggsave("Canopy Cover 1.png") 

#canopy 2
two_canopy <- data %>% 
  filter(Canopy == 2)

table_two <- xtabs(~Ground + Shrub, data= two_canopy)
 
chisq.test(table_two)
table2_freq <- as.data.frame( table_two/sum(table_two) )%>% 
  mutate(cover = 2)

table2_freq %>% 
  ggplot(aes(x = Ground, y = Shrub)) +
  geom_tile(aes(fill = Freq)) +
  scale_fill_viridis_c() +
  coord_fixed() +
  geom_label(aes(label = round(Freq, 3)),
            label.size = 0, # Keep this as is
            color = "white", # Text color
            fill = "#00000010", # Slight background around text to make it more legible
            size = 5) # text size
ggsave("Canopy Cover 2.png")   

#canopy 3
three_canopy <- data %>% 
  filter(Canopy == 3)

table_three <- xtabs(~Ground + Shrub, data= three_canopy)
 
chisq.test(table_three)
table3_freq <- as.data.frame( table_three/sum(table_three) )%>% 
  mutate(cover = 3)

table3_freq %>% 
  ggplot(aes(x = Ground, y = Shrub)) +
  geom_tile(aes(fill = Freq)) +
  scale_fill_viridis_c() +
  coord_fixed() +
  geom_label(aes(label = round(Freq, 3)),
            label.size = 0, # Keep this as is
            color = "white", # Text color
            fill = "#00000010", # Slight background around text to make it more legible
            size = 5) # text size
ggsave("Canopy Cover 3.png") 

#combining
freq_data <- bind_rows(table0_freq, table1_freq, table2_freq, table3_freq) %>% 
  mutate(Ground = factor(Ground, levels = c("0","1","2","3"))) 

freq_data %>% 
  ggplot(aes(x = Ground, y = Shrub)) +
  facet_wrap(facets = vars(cover)) +
  geom_tile(aes(fill = Freq)) +
  scale_fill_viridis_c() +
  coord_fixed() +
  geom_label(aes(label = round(Freq, 3)),
            label.size = 0, # Keep this as is
            color = "white", # Text color
            fill = "#00000010", # Slight background around text to make it more legible
            size = 2.5) # text size
ggsave("Canopy Cover Freq.png")

```


Historical Comparison
```{r}
data1 <- data
data1$year <- "2021"
old_data$year <- "2004"

data_combo <- merge(data1, old_data, all = TRUE)

canopy_compa <- data_combo %>% 
  group_by(year) %>%
  select(year, Canopy) %>% 
  table()
canopy_compa

chisq.test(canopy_compa)

shrub_compa <- data_combo %>% 
  group_by(year) %>% 
  select(year, Shrub) %>% 
  table()
shrub_compa

chisq.test(shrub_compa)

ground_compa <- data_combo %>% 
  group_by(year) %>% 
  select(year, Ground) %>% 
  table()
ground_compa

chisq.test(ground_compa)
  
```






